apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: aymane55/ensagram-backend
          ports:
            - containerPort: 3001
          env:
            - name: MONGODB_URI
              value: "mongodb+srv://Slapjack:CcWGkzHDUx5mB7ac@cluster0.zqeikgz.mongodb.net/test"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
