apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: aymane55/ensagram-frontend
          ports:  
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000 # You can expose the frontend service on port 80
      targetPort: 3000
